import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
  return (
    <html className={dmSans.className}>
      <body>{children}</body>
    </html>
  )
}